[en]
languageCode = "en"
languageName = "English"
contentDir = "../../docs/en"
title = "Holloway's ExperimentingGoWASM"

[zh-hans]
languageCode = "zh-hans"
languageName = "Chinese (Simplified)"
contentDir = "../../docs/zh-hans"
title = "Holloway's GoWASM实验"
