[Metadata]
Name = 'Archive'
Description = """
Monteur's internal archive system consolidating all releases into a directory.
"""
Type = 'archive'




[Variables]

[FMTVariables]




[[Dependencies]]




[Releases]
Target = '{{- .RootDir -}}/docs/.static/wasm'
Checksum = 'sha512'

[Releases.Data]
Path = '{{- .RootDir -}}/docs/.data/releases/archives'
Format = 'toml'

[Releases.Packages.wasmExpGo-Go]
OS = [ "js" ]
Arch = [ "wasm" ]
Source = '{{- .PackageDir -}}/go-wasmExpGo.wasm'

[Releases.Packages.wasmExecJS-Go]
OS = [ "js" ]
Arch = [ "wasm" ]
Source = '{{- .PackageDir -}}/go-wasm_exec.js'

[Releases.Packages.wasmExpGo-TinyGo]
OS = [ "js" ]
Arch = [ "wasm" ]
Source = '{{- .PackageDir -}}/tinygo-wasmExpGo.wasm'

[Releases.Packages.wasmExecJS-TinyGo]
OS = [ "js" ]
Arch = [ "wasm" ]
Source = '{{- .PackageDir -}}/tinygo-wasm_exec.js'




[[CMD]]
Name = "Placeholder"
Type = 'placeholder'
Condition = [ 'all-all' ]
Source = ''
Target = ''
