[WASM.Source]
URL = "/wasm/v0-0-1/tinygo-wasmExpGo.wasm"
Content = """
const go = new Go();
WebAssembly.instantiateStreaming(fetch("[[< .URL >]]"),
	go.importObject
).then(
	(result) => {
		go.run(result.instance);
	}
);
"""

[WASM.JS]
URL = "/wasm/v0-0-1/wasm_exec.js"
Content = """
"""
