[WASM.Source]
URL = "/wasm/v0-0-1/go-wasmExpGo.wasm"
Content = """
if (!WebAssembly.instantiateStreaming) { // polyfill
	WebAssembly.instantiateStreaming = async (resp, importObject) => {
		const source = await (await resp).arrayBuffer();
		return await WebAssembly.instantiate(source, importObject);
	};
}

const go = new Go();

WebAssembly.instantiateStreaming(fetch("[[< .URL >]]"),
	go.importObject
).then(
	(result) => {
		go.run(result.instance);
	}
);
"""

[WASM.JS]
URL = "/wasm/v0-0-1/go-wasm_exec.js"
Content = """
"""
